apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config-map
  namespace: default
data:
  customer.service.spring.datasource.url: jdbc:postgresql://192.168.56.1:5432/customer_service?ssl=true&sslmode=require
  customer.service.spring.datasource.username: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secret
  namespace: default
type: Opaque
stringData:
  customer.service.spring.datasource.password: postgres

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:v1
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: customer-service-config-map
            - secretRef:
                name: customer-service-secret
---
kind: Service
apiVersion: v1
metadata:
  name: customer-service-node-port
  namespace: default
spec:
  type: NodePort
  selector:
    app: customer-service
  ports:
    - port: 8080
      targetPort: 8080