apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: customer-service:v1
          ports:
            - containerPort: 8080